version: '3.7'

services:
  hoge:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/work:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
